### ISSUE TITLE
请问如何在vps上安装一个可以支持https访问的node proxy？

### ISSUE THREAD

**Issue by MassSmith** [gfw-breaker/heroku-node-proxy#5]
您好，怎样在vps上安装一个通过https访问的nodejs proxy？我试着用caddy的proxy / http://mydomain:8080，无法成功，只能用原版node unblocker工作在8080，使用http://mydomain:8080这样的形式。
也试着，直接用您的代码在vps设置，启动时显示：
> nodeunblocker.com@1.0.0 start /root/heroku-node-proxy
> node ./node_modules/gatling/gatling.js ./app.js

Gatling master thread setting up workers to run /root/heroku-node-proxy/app.js and listen on port 8080
Gatling worker thread 1 up and listening

也是工作在8080端口，并未工作在443端口，用caddy也无法反向代理。

**Comment by MassSmith** [comment]
折腾了一下，找到下面的解决办法：
按原版node unblocker的安装方法，在vps上安装heroku-node-proxy，过程如下：
sudo apt update
sudo apt install curl -y
curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt install nodejs -y
sudo apt install build-essential -y
sudo apt install git -y
sudo git clone https://github.com/gfw-breaker/heroku-node-proxy.git
cd heroku-node-proxy
npm install 
npm start 
以上是安装设置heroku-node-proxy到vps中。
安装设置caddy做https前置代理。
caddy配置文件里面添加这样一条配置：

     proxy / localhost:8080 {
        transparent
     }
便可以成功的在vps上运行https的node-proxy。
非常感谢您提供的支持https的node js proxy。
我用原版的node unblocker这样设置，使用过程中发现了问题，有时会打不开页面。但是用您这个修改版，就没有任何问题。

**Comment by gfw-breaker** [comment]
@MassSmith 
我把原版的node unblocker 稍微修改了一下， 把http改为https了。
nodejs默认是运行在8080端口上， 我使用的是nginx做前端， 然后在nginx上配置https， 而且配置了缓存，运行效果很好。

**Comment by MassSmith** [comment]
在线代理打不开www.soundofhope.org 这个网址打不开，出现以下错误

Error 520 Ray ID: 4839d6cfc21445a2 • 2018-12-03 23:33:35 UTC
Web server is returning an unknown error
You
Browser Working  OK
Taipei
Cloudflare Working OK
www.soundofhope.org
Host
Error

如果再通过vpn或者加密socks代理，则能正常打开https://xxx.xxxx.xxx/proxy/http://www.soundofhope.org/
直接访问则出现上述错误提示
这是什么原因？

**Comment by gfw-breaker** [comment]
@MassSmith 是啊，我对CDN的技术不是很了解，目前还没找到具体原因。

**Comment by gfw-breaker** [comment]
@MassSmith 解决了，代理中去掉 X-Real-IP和X-Forwarded-For这两个header就可以了。
CDN好像会校验真正发起请求的IP地址和header中的IP地址信息。

**Comment by MassSmith** [comment]
好的，谢谢，我试试。

**Comment by MassSmith** [comment]
非常感谢，成功了，那么这个在线代理，就很完美了。
Caddy的配置文件，原来proxy改成如下：
    proxy / localhost:8080 {
        header_upstream Host {host}
        header_upstream X-Forwarded-Port {server_port}
        header_upstream X-Forwarded-Proto {scheme}
     }

**Comment by MassSmith** [comment]
还有一个问题，我曾试着把
proxy / localhost:8080 {
其中的"/"改为一个路径地址，不知道为什么，总是不能成功。这是为什么？
比如：
proxy /online localhost:8080 {

浏览器访问：
https://xxx.xxx.xxx/online/proxy/http://xxx.xxx.xxx

**Comment by MassSmith** [comment]
这个问题并不重要，目前来看，我觉得已经很好了。

**Comment by gfw-breaker** [comment]
@MassSmith 我没有用过Caddy哦。Nginx的URL重写机制是可以的，Caddy应该也类似吧。
另外，Caddy有缓存机制吗？如果不支持话，每次用户请求都会调用后端的nodejs程序，会很耗资源。

**Comment by MassSmith** [comment]
这个没想过，我去看看Caddy手册。如果有就更好了，没有也没关系，用上CDN应该也可以起到一些作用。

**Comment by MassSmith** [comment]
比PHP的在线代理好用，代理三退官网，可以成功提交三退名单，PHP的不知道怎么回事，提交出错。

**Comment by MassSmith** [comment]
刚才看了一下Caddy的手册，有缓存功能，启用后，默认的缓存时间是5分钟后过期，这个时间是长还是短？
配置文件里加一个cache就可以，

yoursite.caddy {
    cache
    proxy / localhost:8080
}

更高级的用法是
caddy.test {
    proxy / yourserver:5000
    cache {
        match_path /assets
        match_header Content-Type image/jpg image/png
        status_header X-Cache-Status
        default_max_age 15m
        path /tmp/caddy-cache
    }
}
谢谢你的提醒。

**Comment by MassSmith** [comment]
这个缓存会对提交表单有影响吗？如果有的话，那就还不如不启用。
caddy的缓存机制没有找到说明，不过，Nginx的反向代理缓存，对于http post的影响，这里有一个说明，还有相关的结决办法。
https://my.oschina.net/neochen/blog/1529127

**Comment by gfw-breaker** [comment]
Cache 是受 Cache-Control、Expires这两个response header控制的，如果源头设置不让缓存，那么代理就不会缓存，post的请求一般不让缓存的。对于新闻类的内容，我设的是1天的缓存。

**Comment by MassSmith** [comment]
好的。
